"""Cliquet de couverture « IA au courant de tout » (2026-09-02).

RÈGLE (demande explicite de Phil) : toute NOUVELLE fonctionnalité de
Kratos doit être disponible via la clé API / le connecteur MCP SANS
qu'il ait à le demander. Le test smoke ``test_smoke_couverture_api_ia``
compare les tables du modèle à cette liste : une table inconnue fait
ÉCHOUER la suite tant que son exposition n'est pas réglée.

Quand tu ajoutes une table :
1. Ses ÉCRITURES sont déjà couvertes par le journal automatique
   (audit_middleware) → rien à faire pour les événements.
2. Pour la LECTURE par le Claude de Phil : ajoute l'entité aux
   registres MCP (``_LIST_ENTITIES`` / ``_DETAIL_ENTITIES`` de
   activity.py) ou à un outil MCP dédié si le générique ne convient
   pas.
3. PUIS ajoute le nom de la table à ``TABLES_COUVERTES`` ci-dessous.
   (Une table purement technique — cache, liaison — s'ajoute aussi,
   c'est l'acte de décision qui compte.)
"""

TABLES_COUVERTES: frozenset[str] = frozenset({
    # Tables enregistrées via les endpoints (hors app/models/__init__)
    # — existantes au moment du cliquet.
    "construction_bon_defaults",
    "qbo_connections",
    "user_access_overrides",
    "achats",
    "agenda_events",
    "api_keys",
    "appointment_types",
    "assistant_actions",
    "audit_logs",
    "automation_settings",
    "availability_slots",
    "bon_items",
    "bons_travail",
    "cadence_steps",
    "centris_listings",
    "client_documents",
    "clients",
    "contact_hides",
    "contact_request_photos",
    "contact_requests",
    "contacts",
    "contrat_gestion_template",
    "contrats_gestion",
    "crm_columns",
    "cron_runs",
    "devlog_clients",
    "devlog_contracts",
    "devlog_invoice_items",
    "devlog_invoices",
    "devlog_lead_needs",
    "devlog_leads",
    "devlog_nps_responses",
    "devlog_project_members",
    "devlog_project_phases",
    "devlog_project_photos",
    "devlog_project_purchases",
    "devlog_project_recurring_services",
    "devlog_project_tasks",
    "devlog_projects",
    "devlog_soumission_defaults",
    "devlog_soumission_items",
    "devlog_soumission_modules",
    "devlog_soumission_sections",
    "devlog_soumissions",
    "devlog_sous_traitants",
    "devlog_time_entries",
    "drive_audit_logs",
    "drive_auto_uploads",
    "drive_conventions",
    "drive_entity_links",
    "drive_page_modules",
    "drive_user_tokens",
    "email_logs",
    "email_templates",
    "employe_rate_history",
    "employes",
    "entreprise_finance_snapshots",
    "entreprise_links",
    "entreprise_partners",
    "entreprise_tache_assignees",
    "entreprise_tache_immeubles",
    "entreprise_tache_templates",
    "entreprise_taches",
    "entreprise_value_milestones",
    "entreprise_value_plans",
    "entreprises",
    "esign_attachments",
    "esign_documents",
    "esign_events",
    "esign_fields",
    "esign_observers",
    "esign_signers",
    "esign_template_fields",
    "esign_templates",
    "external_busy_blocks",
    "facture_items",
    "facture_payments",
    "factures",
    "follow_ups",
    "fournisseurs",
    "geocoded_addresses",
    "help_requests",
    "imm_bail_renouvellements",
    "imm_baux",
    "imm_communications",
    "imm_doc_perso_modeles",
    "imm_doc_templates",
    "imm_documents",
    "imm_evaluations",
    "imm_factures_externes",
    "imm_factures_gestion",
    "imm_frais_locatifs",
    "imm_frais_manuels_gestion",
    "imm_hypotheques",
    "imm_immeuble_ownerships",
    "imm_immeubles",
    "imm_locataire_communications",
    # Garants & contacts d'un locataire (2026-09-09) — listés via
    # kratos_list_entities(locataire_contacts) + détail locataire_contact.
    "imm_locataire_contacts",
    "imm_locataires",
    "imm_location_annonces",
    "imm_location_dossiers",
    "imm_location_visites",
    "imm_logements",
    "imm_maintenance_ordres",
    "imm_paiements_externes",
    "imm_paiements_loyer",
    "imm_relances_loyer",
    "imm_releves31",
    # Dossiers TAL (2026-09-09) — kratos_list_entities(tal_dossiers) +
    # détail tal_dossier ; routes REST /immobilier/tal-dossiers.
    "imm_tal_dossiers",
    "immeuble_depenses",
    "inv_distributions",
    "inv_documents",
    "inv_flux",
    "inv_investissements",
    "inv_jalons",
    "inv_participations",
    "inv_projet_profils",
    "kratos_messages",
    "kratos_problems",
    "lead_analyses",
    "lead_analysis_attachments",
    "leave_requests",
    "market_rents",
    "measurement_photos",
    "measurement_snapshots",
    "mtl_property_units",
    "ndas",
    "note_templates",
    "notifications",
    "numbering_counters",
    "offers",
    "optimisation_budget_lignes",
    "optimisation_negos",
    "optimisation_projets",
    "org_nodes",
    "org_versions",
    "project_corrections",
    "project_members",
    "project_phase_assignees",
    "project_phases",
    "project_photos",
    "project_subcontractor_contracts",
    "project_task_assignees",
    "project_tasks",
    "projects",
    "prospection_analyses",
    "prospection_analysis_defaults",
    "prospection_deal_task_assignees",
    "prospection_deal_task_immeubles",
    "prospection_deal_tasks",
    "prospection_deals",
    "prospection_lead_list_members",
    "prospection_lead_lists",
    "prospection_lead_photos",
    "prospection_lead_transactions",
    "prospection_leads",
    "punches",
    "purchase_agreement_templates",
    "purchase_agreements",
    "purchase_order_items",
    "purchase_orders",
    "push_subscriptions",
    "qbo_account_maps",
    "qbo_alias_payeurs",
    "qbo_compte_immeubles",
    "qbo_comptes_loyers",
    "qbo_monthly_invoices",
    "qbo_tokens",
    "qbo_transactions_loyers",
    "qbo_verifs_manuelles",
    "qg_activities",
    "qg_ai_conversations",
    "qg_ai_messages",
    "qg_domains",
    "qg_embeddings",
    "qg_insights",
    "qg_kpis",
    "qg_strategic_projects",
    "qg_summaries",
    "qg_visions",
    "raci_activities",
    "raci_cells",
    "raci_people",
    "raci_poles",
    "raci_subsections",
    "relance_items",
    "relance_plans",
    "rencontre_sections",
    "rencontres",
    "rental_listings",
    "req_companies",
    "role_permissions",
    "sales_task_assignees",
    "sales_tasks",
    "seo_articles",
    "service_template_items",
    "service_templates",
    "sold_comparables",
    "soumission_items",
    "soumissions",
    "sous_traitant_timesheets",
    "sous_traitants",
    "subscription_vault_accesses",
    "subscriptions",
    "teams_meeting_imports",
    "timesheet_companies",
    "timesheet_entries",
    "timesheet_reglements",
    "timesheet_user_rates",
    "timesheets",
    "user_ai_briefs",
    "user_ai_configs",
    "user_business_roles",
    "user_calendar_feeds",
    "user_immeubles",
    "users",
    "voice_business_hours",
    "voice_call_routes",
    "voice_call_transcripts",
    "voice_call_turns",
    "voice_caller_intel",
    "voice_calls",
    "voice_client_presence",
    "voice_filters",
    "voice_phone_numbers",
    "voice_sms",
    "voice_usage_daily",
})
